@SET CPU_FAMILY=0%PROCESSOR_LEVEL%
@SET CPU_FAMILY=%CPU_FAMILY:~-2%
@SET CPU_MODEL=000%PROCESSOR_REVISION%
@SET CPU_MODEL=%CPU_MODEL:~-4%
@SET CPU_FINAL=%CPU_FAMILY%-%CPU_MODEL:~0,2%-%CPU_MODEL:~2,2%
@ECHO unknown (%CPU_FINAL%)